import {MovieReviews} from '../shared/types'

export const moviereviews : MovieReviews[] = [
  {
    MovieId: 848326,
    MovieTitle: 'Rebel Moon - Part One: A Child of Fire',
    ReviewId: 1,
    ReviewerId:'stevo501@gmail.com',
    ReviewDate: '2025-03-15',
    Content: 'Potential Destroyed By Slow Motion. Yes, I know, it is Zack Snyder. If a movie is 90 minutes, he will add 1 hour of slow motion to it, frequently at moments that do not need it. He should take lessons from Xanxia and Wuxia directors on when slow motion actually adds something. The universe built, character development and the potential of the story are just waste on this OCD pressing of the slow motion button. Such a shame.',
  },
  {
    MovieId: 572802,
    MovieTitle: 'Aquaman and the Lost Kingdom',
    ReviewId: 2,
    ReviewerId:'stevowj2004@hotmail.com',
    ReviewDate: '2024-12-03',
    Content: 'DC is trying to copy Marvel instead of listening to their audience',
  },
  {
    MovieId: 695721,
    MovieTitle: 'The Hunger Games: The Ballad of Songbirds & Snakes',
    ReviewId: 3,
    ReviewerId:'s_johnston501@yahoo.com',
    ReviewDate: '2024-01-12',
    Content: 'Pretty good but pretty pointless, as well made but not as good as any of the other hungry games. Essentially a cash grab hidden in a good film. Some good performances though 3.5/5',
  },
  {
    MovieId: 1029575,
    MovieTitle: 'The Family Plan',
    ReviewId: 4,
    ReviewerId:'spacebook849@gmail.com',
    ReviewDate: '2024-01-12',
    Content: 'The Family Plan is an entertaining film, largely due to the charisma of its lead stars. However, the script lacks originality and the plot is predictable, resulting in a forgettable viewing experience. It almost feels as though Apple+ used an AI generator to create a generic spy comedy centered around a family discovering their fathers secret assassin identity. The action sequences are passable, but the story follows such familiar beats that it fails to hold my interest. Thankfully, Mark Wahlberg and Michelle Monaghans performances add some enjoyment to the film, preventing it from being completely dismissible. While I found it enjoyable to watch once, I do not see myself revisiting it. Ghosted offers a more entertaining take on the spy-comedy genre. Nonetheless, if your watchlist is lacking options, Wahlberg and Monaghans presence might make The Family Plan worth a try.',
  },
  {
    MovieId: 787699,
    MovieTitle: 'Wonka',
    ReviewId: 5,
    ReviewerId:'s_johnston501@yahoo.com',
    ReviewDate: '2024-05-12',
    Content: 'This is 100 procent the best Wonka movie. Theres alot of exciting moments in the movie which I appreciate.',    
  },
  {
    MovieId: 891699,
    MovieTitle: 'Silent Night',
    ReviewId: 6,
    ReviewerId:'stevo501@gmail.com',
    ReviewDate: '2023-12-28',
    Content: 'It is a Woo film. Very predictable. Somewhat stale but still got the double guns. Real good double guns mr Detective. I think that was the highlight of the film. No way that guy was listening to that music and dancing like that. I did not really watch the first hour, honestly. It is all pretty background quality.',    
  },
  {
    MovieId: 798141,
    MovieTitle: 'Doors',
    ReviewId: 7,
    ReviewerId:'stevo501@gmail.com',
    ReviewDate: '2023-03-28',
    Content: 'This is a bad film, i just did not care, bad story, bad acting, amateurly made. just dont bother.',    
  },
  {
    MovieId: 872585,
    MovieTitle: 'Oppenheimer',
    ReviewId: 8,
    ReviewerId:'stevo501@gmail.com',
    ReviewDate: '2023-07-26',
    Content: 'This film takes you on an exhilarating journey through history, skillfully weaving together captivating storytelling and breathtaking visuals. The performances were top-notch, leaving me completely immersed in the characters emotions. A definite must-see!',    
  },
  {
    MovieId: 798141,
    MovieTitle: 'Saltburn',
    ReviewId: 9,
    ReviewerId:'spacebook849@gmail.com',
    ReviewDate: '2023-12-27',
    Content: 'Has a case of the samesies on the final chapter. I think we get it. I liked the people. Fun characters outside of you know who. Does anyone really say the vampire line? Great character reveal in the slurp. For me, the explanation station took away from the experience. Feels sloppier the more you see. But then you see it all. Giant slopfest.',     
  },
  {
    MovieId: 466420,
    MovieTitle: 'Killers of the Flower Moon',
    ReviewId: 10,
    ReviewerId:'stevowj2004@hotmail.com',
    ReviewDate: '2023-12-24',
    Content: 'Hats off to Martin Scorsese, once and once again. This right here shows us the real power of cinema.',     
  },
  {
    MovieId: 1071215,
    MovieTitle: 'Thanksgiving',
    ReviewId: 11,
    ReviewerId:'stevowj2004@hotmail.com',
    ReviewDate: '2023-11-19',
    Content: 'Loved this movie and cannot wait to go watch it a second time!! Dive into this horror flick that is a total throwback to those crazy, blood-soaked classics. It is like a blast from the past, but with a fresh, modern vibe. This movie pays respects to the old-school scarefests by mixing gallons of gore with outrageous scenes. What makes it special is how it knows it is a bit over-the-top yet still kinda serious. They use old-school effects that make all the blood and guts feel real. It is like a trip down memory lane, but with a cool new spin-a creepy, fun tribute that feels both familiar and excitingly different.',      
  },
  {
    MovieId: 901362,
    MovieTitle: 'Trolls Band Together',
    ReviewId: 12,
    ReviewerId:'s_johnston501@yahoo.com',
    ReviewDate: '2025-02-26',
    Content: 'Trolls Band Together is a better watch than "Trolls World Tour", even if it still makes for forgettable viewing for me. The characters of Anna Kendrick and Justin Timberlake remain likeable leads, they star in a story that is slightly more interesting than last time out. I must say, and this is not a major deal given these flicks do not exactly aim to be anything more than light family entertainment, that the worldbuilding in these films is rather rubbish. It feels like all three movies are set in differing universes, they look and feel like separate things.That pink eye joke, if only due to Kenan Thompsons part in it as Tiny Diamond, did make me laugh, so at least it produced something. Otherwise, these sequels have fallen flat; not made for me and all that, I know.',     
  },
  {
    MovieId: 385687,
    MovieTitle: 'Fast X',
    ReviewId: 13,
    ReviewerId:'stevo501@gmail.com',
    ReviewDate: '2023-05-21',
    Content: 'Great movie',    
  },
  {
    MovieId: 504148,
    MovieTitle: 'The Serpent',
    ReviewId: 14,
    ReviewerId:'stevo501@gmail.com',
    ReviewDate: '2021-08-02',
    Content: 'I really enjoyed the show. I was not too bothered by those constant time jumps while those seemed to have annoyed quite a lot of people. But those accents...Jenna Coleman speaking french especially. I am french myself so this really annoyed me. Why did not they just cast someone who actually speaks the language?! I like Jenna Coleman, but I think she is just not a great fit here. Otherwise great production.',  
  },
  {
    MovieId: 670292,
    MovieTitle: 'The Creator',
    ReviewId: 15,
    ReviewerId:'spacebook849@gmail.com',
    ReviewDate: '2023-12-25',
    Content: 'Movie had a solid start, but got bogged down in the last half. Kind of a waste since it looked pretty cool.',     
  },
  {
    MovieId: 1143183,
    MovieTitle: 'Rewind',
    ReviewId: 16,
    ReviewerId:'spacebook849@gmail.com',
    ReviewDate: '2023-05-23',
    Content: 'Well-done documentary on a very disturbing subject, with important lessons for all',       
  },
  {
    MovieId: 755401,
    MovieTitle: 'Skydog',
    ReviewId: 17,
    ReviewerId:'stevo501@gmail.com',
    ReviewDate: '2021-10-14',
    Content: 'Entertaining, with a great story line. Sadly, the direction and story board was seriously lacking.',     
  },
  {
    
    MovieId: 897087,
    MovieTitle: 'Freelance',
    ReviewId: 18,
    ReviewerId:'stevo501@gmail.com',
    ReviewDate: '2024-01-01',
    Content: 'Great movie!',
  },
  {
    MovieId: 897087,
    MovieTitle: 'Freelance',
    ReviewId: 19,
    ReviewerId:'spacebook849@gmail.com',
    ReviewDate: '2024-01-01',
    Content: 'Hilarious that on the day Amazon announce the introduction of ads (or a 35% uplift in your monthly fee) that this nonsense hits the small screen. It purports to be a comedy, but I am not sure what language you would have to be speaking in order to get any humour out of this contrived and weakly devised action "thriller". Journalist "Claire" (Alison Brie) hires security specialist "Mason" (John Cena) to accompany her on a trip to a jungle dictatorship where she is to interview the president. Upon arrival they meet the suave and debonaire "Venegas" (Juan Pablo Raba) who has his own golden gun - a little less subtle than that of Christopher Lee! Anyway, no sooner do they land than they find themselves caught up in a coup led by an ambitious but cowardly nephew and must now traipse through the jungle trying to stay one step ahead of the military and of the mercenaries who may or may not be on someones side! This is just a badly conceived mess of a film with the mediocre acting matched only by some dread    ful dialogue amidst a repetitive series of ambushes, shoot-outs and a denouement that rather summed up this confused and derivative story. It is too long, but I am not sure where you would stop cutting if you started, so I would have to recommend that you just go find an episode or two of the "A Team" and sink some Malbec instead.',
    },
  {
    MovieId: 385687,
    MovieTitle: 'Fast X',
    ReviewId: 20,
    ReviewerId:'stevowj2004@hotmail.com',
    ReviewDate: '2023-06-15',
    Content: 'Overall, it was an average action movie and the franchise has reached fatigue.',     
  }
]


